version: "3.8"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: medusaDB
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
